CREATE TABLE PARSER (
    ID SERIAL UNIQUE NOT NULL,
    INN CHAR(10) UNIQUE NOT NULL,
    KPP CHAR(9) UNIQUE NOT NULL,
    OGRN CHAR(13) UNIQUE NOT NULL,
    ShortName VARCHAR(100) NOT NULL,
    FullName VARCHAR(1000) NOT NULL,
    Director VARCHAR(500) NOT NULL
);

SELECT * FROM PARSER;

DROP TABLE PARSER;